### ISSUE TITLE
Tkinter is an unnanounced but required dependency

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#247]
* `brownie` Version: 1.1.0
* Python Version: 3.7.5
* OS: linux

### What was wrong?
```bash
$ brownie init
Traceback (most recent call last):
  File "/home/bryant/.pyenv/versions/plasma-cash/bin/brownie", line 5, in <module>
    from brownie._cli.__main__ import main
  File "/home/bryant/.pyenv/versions/3.7.5/envs/plasma-cash/lib/python3.7/site-packages/brownie/__init__.py", line 4, in <module>
    from brownie._gui import Gui
  File "/home/bryant/.pyenv/versions/3.7.5/envs/plasma-cash/lib/python3.7/site-packages/brownie/_gui/__init__.py", line 3, in <module>
    from .root import Root as Gui  # noqa: F401
  File "/home/bryant/.pyenv/versions/3.7.5/envs/plasma-cash/lib/python3.7/site-packages/brownie/_gui/root.py", line 4, in <module>
    import tkinter as tk
  File "/home/bryant/.pyenv/versions/3.7.5/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

### How can it be fixed?
This should be an optional feature. If detected, then the coverage system GUI should be available. If not, either disable it entirely or write to files/terminal for your viewing pleasure.

**Comment by fubuloubu** [comment]
According to https://github.com/pyenv/pyenv/issues/94#issuecomment-31371552, just install `tk-dev` _before_ compiling Python to get access to this missing package.

**Comment by iamdefinitelyahuman** [comment]
Thanks for letting me know!  I like the idea of only installing it if tkinter is detected.  Once https://github.com/iamdefinitelyahuman/brownie/issues/230 is implemented the GUI can become a sort of first-class plugin that's installed by default if the dependencies are there.

**Comment by njgheorghita** [comment]
[This one](https://github.com/pyenv/pyenv/issues/1375#issuecomment-524280004) finally got things working for me, just leaving it here for reference.
